gytis-ivaskevicius/flake-utils-plus

- examples/fully-featured-flake.nix
- systemFlake.nix
Generic argument to add defaults to all hosts. This could cover modules, extraArgs, system, and channelName. I would say keep some things, ex `sharedModules`, just for convenience and backwards-compatibility, but this is overall useful to prevent making the api surface too large. Whenever adding things to hosts, you no longer need to make a relevant default argument, users can just use `defaultHostAttrs`.
Example:
```nix
defaultHostAttrs = {
modules = ...;
channeName = ...;
system = ...;
};
```
> Add argument for default host attributes

- systemFlake.nix
Rationale:
For internal coding purposes only, the following attribute set does
not require an abstract name (such as `profile`). Moreover so, as
"profile" has a distinct legacy meaning in the nix ecosystem.
```nix
{
channelName = "...";
system = "...";
extraArgs = {};
modules = [];
}
```
Instead, this PR renames it to a banal and descriptive `hostAttrs`. This
naming does also better align with the top level `defaultHostAttrs`.
> ref: `profile` -> `hostAttrs`

- examples/fully-featured-flake.nix
- examples/somewhat-realistic-flake.nix
- systemFlake.nix
---
As the `fup` api grows, we need a better way to ensure consistency.
Currently top level has a mix of host-specific and channel-specific defaults. However, we expect host specific defaults to grow in the near future (eg. #17) and it would not be in order to just clutter the top level arguments.
This PR introduces a (reusable) API container and thereby transparently exposes the current `profile/host` `fup`-API-objet. For clarity, it currently is:
```nix
{
profile = {
channelName = "...";
system = "...";
extraArgs = {};
modules = [];
};
}
```
This PR generalizes this API, implements a minimal validation (expected args of the profile/host API object are present and unexpected args aren't) and consequentially, applies it analogously to a new `defaultHostAttrs`.
`defaultsHostAttrs` …
> add: defaultHostsAttrs (fixed)

- README.md
- examples/fully-featured-flake.nix
- examples/somewhat-realistic-flake.nix
- systemFlake.nix
This allows users to pass the config system they want a profile built with and the output it should go in.
So you could now do:
```
configProfiles.NixOS = {
builder = inputs.darwin.lib.darwinSystem;
output = "darwinConfigurations";
}
```
Also added `defaultConfigBuilder` and `defaultConfigOutput` to make this a bit easier for those that only use one system. And renamed `nixosProfiles` to `configProfiles` with the proper deprecation line. But I actually think this should be named `hosts`, and then we can go `defaultHostOutput`. Or maybe configs could work.
This will prevent flake-utils-plus making an opinion on what config system, but nixos support is probably a bit better. And this should allow for darwin and home manager support. This could also work for robotnix,  but that would require …
> Allow config system customization

- systemFlake.nix
anything that is going to be passed to an `imports = []` necesarily
needs to be passed as specialArgs. This ensures it does not become
part of the module system (extraArgs = _module.args) itself.
Since it is not part of the module system, modules can evaluate based on
inputs, otherwise no fixed point would exists (infinit recursion).
This is a way to encapsulate profiles into bundles that are accessible
like so:
inputs = [ bundles.home ];
> imp: add specialArgs

- examples/fully-featured/flake.nix
- examples/somewhat-realistic/flake.nix
- systemFlake.nix
Create a merge function that can deal with attrsets and lists and use it for:
- merging host arguments
- configuration outputs - use it in foldHosts and allow for nixosConfigurations escape hatch
Also fix the issue of packagesBuilder overriding `otherArguments.packages`, by merging each output manually with mkOutput function. Also cleans up the output merging code, its just two strings passed to a function. This doesn't require the merge function.
> Improve merging of host arguments and flake outputs

- README.md
- flake.nix
- moduleFromListExporter.nix
- overlaysFromChannelsExporter.nix
- packagesFromOverlaysBuilderConstructor.nix
- systemFlake.nix
This is a convenient function that enables sane default sharing of channel overlays:
- It filters on packages per channel, that are also defined in overlays
- therefore, only "custom" stuff that adds potential value to the world is exported
```nix
{
self.packages."<system>" = {
kakoune = { ... };
};
}
```
----
checpoint w/o the following:
- cleanup / refactoring
- docstrings
- tackle nixpkgs.lib-is-not-cheap-to-import-issue
- discuss packageBuilder api extension with `channels`
> implement builtinPackagesBuilder

- systemFlake.nix
fixes this issue:
```
nix-repl> flake.defaultApp
{ aarch64-linux = { ... }; x86_64-linux = { ... }; }
nix-repl> flake.defaultApp.aarch64-linux
{ }
```
All outputs were created regardless if there is a builder passed for it. This wraps both the otherArguments.packages.system and the builder in an `optionalAttrs` and uses `mergeAny` to properly merge the two.
> fix issue with creating empty outputs

- .gitignore
- examples/fully-featured/configurations/Morty.host.nix
- examples/somewhat-realistic/hosts/One.nix
- examples/somewhat-realistic/hosts/Two.nix
This makes the hosts in the examples properly evaluate by giving them a root filesystem and boot loader. With this, the `somewhat-realistic` example passes `nix flake check` - depends on #38. The hosts of `fully-featured` should now pass, but the flake itself doesn't, because of the IFD that comes with nixpkgs patching.
Also added the flake.lock's in the example flakes to .gitignore. I assume we don't want to commit those, but they have to be there to test things.
> Make the example hosts pass assertions

- .github/workflows/ci.yaml
- examples/fully-featured/configurations/Summer.host.nix
- examples/fully-featured/flake.nix
- examples/fully-featured/myNixpkgsPatch.patch
- systemFlake.nix
As far as I can tell, these changes allow patching NixOS and configuring `nixpkgs.config` in the host's modules. I was able to evaluate (and switch to) my nixos config which uses both correctly.
I'll clean this up some more and maybe demonstrate the different possibilities in the fully featured example flake. (That will have to wait until tomorrow though, it's quite late here.)
Fixes #4.
> Use nixos modules and lib from patched nixpkgs and allow setting nixpkgs.config values in host modules

- examples/fully-featured/configurations/Morty.host.nix
- systemFlake.nix
a module. imports = [ ${myChannelModulesPathk}/installer/...
This allows users to relatively conveniently pull in modules from other channels. The chances of success are mixed depending on the channel distance, but if it works, it's great.
> imp: provide per channel modules paths to make it easy to "backport"

- examples/somewhat-realistic/flake.nix
- flake.lock
- overlaysFromChannelsExporter.nix
- packagesFromOverlaysBuilderConstructor.nix
This is some fixups and improvments to the api for the overlaysFromChannelsExporter and packagesFromOverlaysBuilderConstructor. 
Have overlays exporter take `self.pkgs` and `inputs`. The former is so nixpkgs sets are instantiated and the overlay lists are ready. The latter is to auto filter any overlays that were taken from inputs. Its not good to export things that weren't originated in your flake and you don't plan on maintaining.
Change packages builderConstructor to just take an attrset of overlays and the builder can then pull out packages defined in overlays from the channels set.
> General exporter and builderConstructor improvements

- examples/fully-featured/configurations/Rick.host.nix
- systemFlake.nix
gives both builders and hosts information about what channel their on. The former is so you can implement channel-specific logic in a builder. In devos we have a extended nixosSystem, so we would want to do `specialArgs.channel.input.lib.nixosSystem`, to ensure we are using the write channel for that host. And modules can do logic to hosts based on what channel the host is on.
> embed info in channels and pass host's channel as specialArg

- examples/somewhat-realistic/flake.nix
- overlaysFromChannelsExporter.nix
This adds the ability to create overlays that aren't exported. You just have to add an attribute called "__dontExport" and the overlaysFromChannelsExporter will filter it out.
As much as I like the auto-exporting overlays, it is kind of frustrating that there is no way out. The other solution is to try and pass the overlay to `inputs` which is needlessly complicated.
```
final: prev: {
firefox = prev.firefox.override { privacySupport = true; };
__dontExport = true;
}
```
vs
```
{ pkgs = self.pkgs; inputs = inputs // { internalOverlays.overlays.firefox = _: _: { firefox = null; }; }
```
> Option to not export overlay

- systemFlake.nix
this allows systemFlake to be called multiple times without having to pass `channels` each time. As long as it just uses self.pkgs, nixpkgs will only get evaluated once and all systemFlake calls use the same channels set
I'm thinking something like this:
```
let
darwinSystems = systemFlake {
inherit self inputs;
hostDefaults = { builder = nix-darwin.lib.darwinSystem; };
hosts = { Morty = { modules = [ ./Morty.nix; ]; }; };
};
nixosSystems = systemFlake {
inherit self inputs;
hosts = { Morty = { modules = [ ./Morty-nixos.nix ]; }; };
};
in
systemFlake {
inherit self inputs;
inherit (darwinSystems) darwinConfigurations;
inherit (nixosSystems) nixosConfigurations;
channels = ...
}
```
> always use self.pkgs instead of channels

- systemFlake.nix
This doesn't hurt in any way, but prevents export for those who use
overlaysFromChannelsExporter
> set __dontExport to srcs overlay

- src/fromOverlays.nix
sub-systems are not great for flakes ecosystems and this prevents
exporting overriden sub-systems from nixpkgs
> fromOverlays: opt-in for exporting sub-systems

- lib/systemFlake.nix
- tests/hosts-config/flake.nix
- tests/testing-utils.nix
Implements naming `nixosConfigurations` like so:
`"com.example.myhost"` and automatically sets the `networking.domain` option if declared this way.
`nixosConfigurations."com.example.myhost"`
I chose reverese dns notation a) for proper grouping (e.g. in a repl) and b) since at this stage they alias a host's config, not precisely a host's IP, like normal DNS would.
> Add support for reverse DNS hostname declarations

- lib/systemFlake.nix
overlays get appended by nixpkgs module
creates problems with overlays that apply patches, since they try to get applied twice.
> fix: don't append overlays manually when passing pkgs

- lib/repl.nix
- lib/systemFlake.nix
Resolve #76 #77
I left `ca-references` in since I am not sure why it is there and I am afraid to remove it. 
If I recall correctly at some point `ca-references` were required for flakes for some reason thus was erroring out for me. Maybe it was a bug or some odd config. Not sure.
> Add mkDefault to extra-options

- devShell.nix
- lib/systemFlake.nix
- tests/derivation-outputs/flake.nix
> imp: make system output dynamic

- .github/workflows/ci.yaml
- README.md
- devShell.nix
- flake.lock
- lib/mkFlake.nix
- lib/repl.nix
Also, does this more or less summarize everything in staging?
```md
Improvements:
- Now overlays receive `srcs` option by default which represents Github repositories from inputs
- `channels.*.input` is no longer required. By default it gets autogenerated from `inputs`
Deprecations:
- Updated fup-repl implementation, now it is a package and can load flake references by path.
- Replaced xyzBuilder(s) with `outputsBuilder`.
- Replaced `saneFlakeDefaults` nixosModule with `nix.generateRegistryFromInputs` option (set it to `true` to enable it)
Implemented multiple exporters: (Please see examples on the project page!)
- `lib.exportModules` - Helper that builds attribute set of modules from paths.
- `lib.exportOverlays` - Helper that builds namespaced attribute set of overlays.
- …
```
> Preparing for release

- lib/mkFlake.nix
to avoid this issue output: `warning: unknown experimental feature 'ca-references'`
> remove ca-references on nix2.5pre

- flake.nix
I recently realized that there's little difference between NixOS,
nix-darwin and home-manager's module systems, so modules should work
across them as long as the options are implemented.
> Export `autoGenFromInputs` module for `nix-darwin`

- README.md
See discussion in https://github.com/gytis-ivaskevicius/flake-utils-plus/issues/113#issuecomment-1065546703
> docs: nix-darwin builder workaround no longer necessary

- examples/home-manager+nur+neovim/flake.nix
- flake.nix
- lib/genPkgOverlay.nix
This is a function to make it easier to add packages from flakes that don't have an `overlay` output. And its also useful if you prefer using the the exported package from a flake instead of the overlay. There are some good reasons for doing this: cache hits, reproducibility, overlay is failing with your channel.
I was thinking of making this an api argument for fup or digga, but I think a lib function is the cleanest way of doing this. I can't think of a good name, so suggestions are welcome.
> Add function, genPkgOverlay, to create an overlay for an input's package

- lib/mkFlake.nix
Not sure if it adapts to the changes(https://github.com/numtide/devshell/pull/259) but at least it doesn't explode.
Fixes #133
> 🐛 Check all attributes for devshell legacyPackages

- lib/mkFlake.nix
Fix gytis-ivaskevicius/flake-utils-plus#136, caused by NixOS/nixpkgs#257458
> fix passing nixpkgs.config if nixpkgs.pkgs.config is present

- lib/mkFlake.nix
Fixes #142 
Note that other modules could conceivably be affected if they read the value of `config.nixpkgs.config`, but I find that exceedingly unlikely.
> fix: Override option nixpkgs.config to avoid failed assertion

- devShell.nix
- lib/exportPackages.nix
- lib/internal-functions.nix
- lib/mkFlake.nix
- lib/options.nix
Hi Gytis and others :wave:
I was wondering whether I could make `flake-utils-plus` load flake parts modules and/or vice versa, and found these unused bindings with https://github.com/oxalica/nil, so I figured I'd help out a tiny bit with this little cleanup first.
Flake parts is intended to be a mostly unopinionated common interface that helps with interoperability between pieces of Nix logic people write and publish for reuse. Users of `flake-utils-plus` benefit from this, as it makes arbitrary other flake-based functionality easy to import, so that they don't have to cobble up custom glue code to merge the flake outputs and then still be stuck with two frameworks that don't actually share things like packages very well.
I'll set it up so that it doesn't add a flake inputs dependency on …
> chore: Remove unused bindings
